"""
Seed data for the Nail Art Academy.
Contains comprehensive initial data for tutorials, materials, tools, and categories.
"""
import json
from datetime import datetime


def get_categories():
    return [
        {"id": 1, "name": "basic", "name_cn": "基础入门", "icon": "sparkles", "description": "新手必备的美甲基础知识与入门技巧", "sort_order": 1},
        {"id": 2, "name": "gel", "name_cn": "甲油胶美甲", "icon": "palette", "description": "各色甲油胶上色技法与款式教学", "sort_order": 2},
        {"id": 3, "name": "french", "name_cn": "法式美甲", "icon": "wand", "description": "经典法式与创意法式美甲教程", "sort_order": 3},
        {"id": 4, "name": "gradient", "name_cn": "渐变美甲", "icon": "droplets", "description": "单色渐变/双色渐变/多色渐变技法", "sort_order": 4},
        {"id": 5, "name": "cat-eye", "name_cn": "猫眼美甲", "icon": "magnet", "description": "磁铁猫眼效果制作技法大全", "sort_order": 5},
        {"id": 6, "name": "3d-nail", "name_cn": "3D浮雕美甲", "icon": "box", "description": "立体雕花、浮雕、镶嵌等3D美甲技法", "sort_order": 6},
        {"id": 7, "name": "marble", "name_cn": "大理石纹美甲", "icon": "waves", "description": "水染大理石纹与手绘大理石纹技法", "sort_order": 7},
        {"id": 8, "name": "extension", "name_cn": "延甲/甲片", "icon": "ruler", "description": "延长甲制作、甲片粘贴、塑形技巧", "sort_order": 8},
        {"id": 9, "name": "nail-art", "name_cn": "美甲彩绘", "icon": "brush", "description": "手绘花朵、线条、图案等彩绘技法", "sort_order": 9},
        {"id": 10, "name": "wearable", "name_cn": "穿戴甲", "icon": "hand", "description": "穿戴甲制作教程与佩戴技巧", "sort_order": 10},
        {"id": 11, "name": "care", "name_cn": "甲面养护", "icon": "heart", "description": "指甲健康养护、甲面修复、营养护理", "sort_order": 11},
        {"id": 12, "name": "tools-guide", "name_cn": "工具使用教学", "icon": "wrench", "description": "各类美甲工具的正确使用方法", "sort_order": 12},
    ]


def get_tags():
    return [
        {"id": 1, "name": "新手入门"},
        {"id": 2, "name": "进阶技法"},
        {"id": 3, "name": "专业级"},
        {"id": 4, "name": "日系"},
        {"id": 5, "name": "韩系"},
        {"id": 6, "name": "欧美风"},
        {"id": 7, "name": "国风"},
        {"id": 8, "name": "春夏款"},
        {"id": 9, "name": "秋冬款"},
        {"id": 10, "name": "婚甲"},
        {"id": 11, "name": "日常通勤"},
        {"id": 12, "name": "约会款"},
        {"id": 13, "name": "显白"},
        {"id": 14, "name": "短甲适合"},
        {"id": 15, "name": "长甲适合"},
    ]


def get_tutorials():
    return [
        {
            "id": 1, "title": "新手美甲全流程 — 从修甲到封层零基础入门",
            "slug": "beginner-full-process",
            "category_id": 1, "difficulty": "beginner",
            "description": "完整的新手美甲流程教学，涵盖修甲、底胶、上色、封层每一步。适合零基础的美甲爱好者。学完即可独立完成基础美甲。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 25,
            "steps": json.dumps([
                {"order": 1, "title": "工具准备", "content": "准备美甲搓条、海绵抛、底胶、甲油胶、封层、光疗灯、清洁液、棉花片等基础工具。", "image": ""},
                {"order": 2, "title": "修整甲型", "content": "用指甲刀修剪至理想长度，用搓条修整甲缘形状。常见甲型：方圆形、椭圆形、杏仁形。初学者推荐方圆形。", "image": ""},
                {"order": 3, "title": "打磨甲面", "content": "用海绵抛轻打磨甲面，去除油脂层。注意：只需轻轻打磨至哑光即可，不要过度打磨伤甲。", "image": ""},
                {"order": 4, "title": "清洁甲面", "content": "用清洁液或酒精棉片擦拭甲面，去除粉尘和油脂。确保甲面完全干燥后再进行下一步。", "image": ""},
                {"order": 5, "title": "涂抹底胶", "content": "薄涂一层底胶，注意避开指缘皮肤。光疗灯照30-60秒固化。底胶起到增加附着力和保护甲面的作用。", "image": ""},
                {"order": 6, "title": "第一层上色", "content": "薄涂第一层甲油胶，颜色要均匀。边缘可以留0.5mm空隙防止溢胶。光疗灯照30-60秒。", "image": ""},
                {"order": 7, "title": "第二层上色", "content": "涂第二层甲油胶增加颜色饱和度。同样薄涂均匀，照灯固化。深色系通常两层即可，浅色系可能需要三层。", "image": ""},
                {"order": 8, "title": "涂抹封层", "content": "均匀涂抹封层胶，包裹甲缘增加持久度。照灯60-90秒。封层分擦洗封层和免洗封层，新手推荐免洗封层。", "image": ""},
                {"order": 9, "title": "完成与养护", "content": "用指缘油涂抹甲周皮肤，按摩吸收。美甲完成！正常可保持1-2周。", "image": ""},
            ]),
            "tips": json.dumps([
                "每层胶一定要薄涂，厚涂会导致缩胶或起皱",
                "照灯时间要充足，未完全固化会导致起翘脱落",
                "底胶和封层一定要包裹甲缘（包边），延长持久度",
                "上色时先涂中间再涂两侧，更容易涂匀",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4, 5, 6]),
            "materials_needed": json.dumps([1, 2, 3, 4]),
            "tags": [1, 14],
        },
        {
            "id": 2, "title": "经典白色法式美甲 — 优雅永不过时",
            "slug": "classic-french-tip",
            "category_id": 3, "difficulty": "intermediate",
            "description": "手把手教你画出完美的法式微笑线。从传统白色法式到现代彩色法式，掌握法式美甲的核心技法。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 30,
            "steps": json.dumps([
                {"order": 1, "title": "底色准备", "content": "完成基础修甲后，涂一层透明底胶或裸粉色打底，照灯固化。法式美甲底色以自然透明感为主。", "image": ""},
                {"order": 2, "title": "画微笑线（方法一：贴纸辅助）", "content": "使用法式贴纸贴在指甲上，露出指尖部分。用白色甲油胶涂抹指尖，撕下贴纸即得完美弧线。适合新手。", "image": ""},
                {"order": 3, "title": "画微笑线（方法二：手绘）", "content": "用细毛笔蘸白色彩绘胶，从指甲一侧起笔，沿自然微笑线弧度画向中间，再从另一侧起笔画向中间汇合。", "image": ""},
                {"order": 4, "title": "修整弧线", "content": "用清洁液蘸取小笔修正不完美的地方，让微笑线弧度流畅自然。照灯固化。", "image": ""},
                {"order": 5, "title": "封层收尾", "content": "涂抹封层包裹整个甲面，照灯60秒。法式美甲完成！", "image": ""},
            ]),
            "tips": json.dumps([
                "微笑线弧度应跟随指甲自然弧度，不要太直或太弯",
                "新手强烈推荐使用法式贴纸/辅助贴，成功率大幅提升",
                "彩色法式（红、粉、蓝等）比传统白色更活泼时尚",
                "V型法式和斜法式也是热门变体，掌握基础后可尝试",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4, 7, 9]),
            "materials_needed": json.dumps([1, 2, 5, 6]),
            "tags": [4, 10, 11],
        },
        {
            "id": 3, "title": "猫眼美甲制作全攻略 — 磁铁技法详解",
            "slug": "cat-eye-magnet-tutorial",
            "category_id": 5, "difficulty": "intermediate",
            "description": "猫眼美甲的核心在于磁铁的使用技巧。本教程讲解如何用磁铁控制猫眼粉的排列，打造迷人猫眼光带效果。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 25,
            "steps": json.dumps([
                {"order": 1, "title": "底色打底", "content": "涂黑色或深色底胶可以让猫眼效果更加明显。照灯固化。深色底色能让猫眼光带对比度更强。", "image": ""},
                {"order": 2, "title": "涂抹猫眼胶", "content": "薄涂一层猫眼甲油胶，不要照灯！趁胶未干时进行磁铁操作。", "image": ""},
                {"order": 3, "title": "磁铁吸附（经典直线猫眼）", "content": "将磁铁平行悬于甲面上方约2-3mm处，保持5-10秒。猫眼粉会被吸附形成一道光带。磁铁越近效果越强。", "image": ""},
                {"order": 4, "title": "磁铁吸附（斜线/曲线效果）", "content": "改变磁铁角度可以做出斜线猫眼。用圆形磁铁靠近可做出圆形光晕效果。创意磁铁摆放可做出各种猫眼图案。", "image": ""},
                {"order": 5, "title": "照灯固化", "content": "磁铁效果满意后，快速放入光疗灯照60秒固化。注意：移动手指时要平稳，避免磁粉移位。", "image": ""},
                {"order": 6, "title": "封层保护", "content": "涂抹封层，照灯60秒。猫眼美甲完成！", "image": ""},
            ]),
            "tips": json.dumps([
                "猫眼胶一定要在未照灯状态下操作磁铁",
                "每只手指单独操作：涂胶→磁铁→照灯，不要一次涂完五只",
                "磁铁距离越近、时间越长，猫眼光带越明显",
                "猫眼胶颜色选择：银色猫眼最经典，彩色猫眼更时尚",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4, 10]),
            "materials_needed": json.dumps([1, 2, 7, 8]),
            "tags": [2, 4, 12],
        },
        {
            "id": 4, "title": "双色渐变美甲 — 海绵渐变技法",
            "slug": "gradient-sponge-technique",
            "category_id": 4, "difficulty": "intermediate",
            "description": "使用化妆海绵打造自然柔美的双色渐变效果。从配色原理到操作技巧，一节课学会渐变美甲。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 20,
            "steps": json.dumps([
                {"order": 1, "title": "配色选择", "content": "选择同色系或邻近色搭配渐变效果最自然。如：粉+白、蓝+紫、裸色+白。对比色搭配更有视觉冲击力。", "image": ""},
                {"order": 2, "title": "底色打底", "content": "涂白色或浅色底胶，照灯固化。白色底色能让渐变色更显色。", "image": ""},
                {"order": 3, "title": "海绵上色", "content": "将两种甲油胶并排涂在化妆海绵上，中间略微重叠。然后将海绵轻轻按压在甲面上，颜色自然过渡。", "image": ""},
                {"order": 4, "title": "重复叠加", "content": "重复海绵按压2-3次增加颜色饱和度和渐变层次感。每次按压后检查渐变效果，不理想可再次叠加。", "image": ""},
                {"order": 5, "title": "清理边缘", "content": "用清洁液蘸取小笔或棉签，清理指甲周围皮肤的溢胶。照灯60秒固化。", "image": ""},
                {"order": 6, "title": "封层收尾", "content": "涂抹封层，让渐变表面更加平整光滑。照灯60秒。渐变美甲完成！", "image": ""},
            ]),
            "tips": json.dumps([
                "海绵选择密度高的化妆海绵，孔太大效果不细腻",
                "每层渐变按压后先照灯10秒半固化，再做下一层层次感更好",
                "渐变方向可以上下渐变、左右渐变、对角渐变",
                "加入亮片或闪粉在渐变过渡处增加精致感",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4, 11]),
            "materials_needed": json.dumps([1, 2, 9, 10]),
            "tags": [2, 5, 12],
        },
        {
            "id": 5, "title": "3D立体雕花美甲 — 浮雕花朵技法",
            "slug": "3d-flower-sculpting",
            "category_id": 6, "difficulty": "advanced",
            "description": "使用雕花胶制作立体花朵装饰。从调胶、塑形到上色，打造精致的3D浮雕美甲效果。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 40,
            "steps": json.dumps([
                {"order": 1, "title": "雕花胶准备", "content": "取适量3D雕花胶，用雕花笔蘸取少量清洁液防止粘连。雕花胶有透明、白色和彩色可选。", "image": ""},
                {"order": 2, "title": "制作花瓣", "content": "取一小团雕花胶搓成水滴形，用雕花笔压扁塑造成花瓣形状。每片花瓣大小要均匀一致。", "image": ""},
                {"order": 3, "title": "组装花朵", "content": "在甲面上先放置花心（小球），围绕花心依次贴上花瓣。一朵花通常5-6片花瓣。照灯30秒半固化。", "image": ""},
                {"order": 4, "title": "添加层次", "content": "可叠加第二层花瓣制作重瓣花效果。添加叶片和藤蔓增加立体感。", "image": ""},
                {"order": 5, "title": "上色点缀", "content": "用彩绘笔蘸取彩色胶为花瓣上色，花心点缀亮钻或珍珠。照灯60秒完全固化。", "image": ""},
                {"order": 6, "title": "封层保护", "content": "用免洗封层小心涂抹3D部分，注意不要破坏立体形状。照灯完成！", "image": ""},
            ]),
            "tips": json.dumps([
                "雕花胶稍硬于一般胶，需要练习手感",
                "花瓣大小要配合指甲大小，小甲面建议做半花/边花",
                "3D美甲日常要避免硬物碰撞，不然容易损坏",
                "初学可从简单的立体蝴蝶结/爱心开始，再进阶到花朵",
            ]),
            "tools_needed": json.dumps([1, 2, 4, 8, 12]),
            "materials_needed": json.dumps([1, 11, 12, 13]),
            "tags": [3, 5, 15],
        },
        {
            "id": 6, "title": "大理石纹美甲 — 水染与手绘两种技法",
            "slug": "marble-nail-art",
            "category_id": 7, "difficulty": "advanced",
            "description": "学习两种大理石纹制作方法：水染拉花法和手绘纹理法。打造高雅的大理石纹美甲效果。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 35,
            "steps": json.dumps([
                {"order": 1, "title": "水染法准备", "content": "准备一杯常温水（约25°C），选择2-3种颜色的甲油胶。在杯子中滴入胶液使其在水面扩散。", "image": ""},
                {"order": 2, "title": "拉花纹路", "content": "用牙签或拉花针在水面轻轻划动，创造出大理石般的纹理图案。注意动作要轻柔！", "image": ""},
                {"order": 3, "title": "转印到甲面", "content": "将指甲面朝下轻轻接触水面花纹，花纹会转印到甲面上。取出后清理周围皮肤。照灯60秒固化。", "image": ""},
                {"order": 4, "title": "手绘法（替代方案）", "content": "涂好底色后，用极细笔蘸深色胶画出不规则纹理线条。再用稀释液晕染边缘，模拟大理石纹效果。", "image": ""},
                {"order": 5, "title": "封层完成", "content": "涂抹封层保护纹路，照灯60秒。大理石纹美甲高贵典雅！", "image": ""},
            ]),
            "tips": json.dumps([
                "水染法水温很重要，太冷太热都会影响扩散效果",
                "经典大理石配色：白+灰、白+黑、白+金",
                "水染法需要快速操作，颜色在水中太久会凝固",
                "手绘法虽然耗时但效果更可控，适合追求完美的用户",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4, 7, 13]),
            "materials_needed": json.dumps([1, 2, 14, 15]),
            "tags": [3, 6, 15],
        },
        {
            "id": 7, "title": "穿戴甲DIY — 从制作到佩戴全教程",
            "slug": "wearable-nails-diy",
            "category_id": 10, "difficulty": "beginner",
            "description": "学会自己制作和佩戴穿戴甲。成本低、可重复使用、随时更换款式。非常适合美甲爱好者和想创业的小伙伴。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 30,
            "steps": json.dumps([
                {"order": 1, "title": "准备甲片", "content": "选择合适的甲片尺寸，用小搓条轻轻打磨甲片内侧增加附着力。选择与真甲弧度匹配的甲片。", "image": ""},
                {"order": 2, "title": "甲片打底", "content": "在甲片上涂底胶、上色、做款式，与正常美甲流程相同。可以做得比普通美甲更精致华丽。", "image": ""},
                {"order": 3, "title": "制作果冻胶佩戴法", "content": "选择合适大小的果冻胶贴贴在真甲上，撕掉保护膜，将穿戴甲按压上去保持10秒。适合短期佩戴(1-3天)。", "image": ""},
                {"order": 4, "title": "胶水佩戴法（持久型）", "content": "在真甲和穿戴甲内侧各涂少量专用胶水，对准贴上按压30秒。可保持1-2周。注意胶水用量不要过多。", "image": ""},
                {"order": 5, "title": "卸除方法", "content": "果冻胶：温水泡5-10分钟，从甲缘轻轻撬起取下。胶水：用解胶剂滴入缝隙，待胶水溶解后取下。", "image": ""},
            ]),
            "tips": json.dumps([
                "穿戴甲尺寸一定要选对，太大容易掉，太小不舒服",
                "制作时可以一次做多套，轮换佩戴",
                "果冻胶适合拍照/约会短期使用，胶水适合长期佩戴",
                "卸下的穿戴甲可以清洁后重复使用",
            ]),
            "tools_needed": json.dumps([1, 2, 14, 15]),
            "materials_needed": json.dumps([1, 2, 16, 17]),
            "tags": [1, 11, 12, 14],
        },
        {
            "id": 8, "title": "美甲工具完全指南 — 从入门到专业工具详解",
            "slug": "nail-tools-complete-guide",
            "category_id": 12, "difficulty": "beginner",
            "description": "全面了解各类美甲工具的用途、选购建议和使用方法。新手该买什么？专业级工具怎么选？一节课搞清楚。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 20,
            "steps": json.dumps([
                {"order": 1, "title": "基础修剪工具", "content": "指甲刀（大号+小号）、死皮剪、死皮推、指甲锉/搓条。选购要点：不锈钢材质、刀口锋利、握感舒适。", "image": ""},
                {"order": 2, "title": "打磨工具", "content": "海绵抛（粗/细双面）、抛光条。粗面修型、细面抛光。电动打磨机适合专业人士，新手手动即可。", "image": ""},
                {"order": 3, "title": "光疗灯", "content": "UV灯或LED灯，用于固化甲油胶。推荐LED灯（36W以上），固化速度快、不伤手。UV灯固化慢但兼容性广。", "image": ""},
                {"order": 4, "title": "彩绘工具", "content": "拉线笔（极细线条）、彩绘笔（图案绘制）、点珠笔（圆点/波点）、扇形笔（渐变扫色）。", "image": ""},
                {"order": 5, "title": "辅助工具", "content": "法式贴纸、美甲贴纸、亮钻/珍珠拾取笔、清洁液/酒精、棉花片、指缘油。这些是提升效率和效果的必备品。", "image": ""},
            ]),
            "tips": json.dumps([
                "新手套装通常￥50-100就能满足基础需求",
                "光疗灯是最值得投资的工具，建议直接买LED 48W以上的",
                "工具每次使用后要清洁消毒，尤其是死皮剪",
                "搓条和海绵抛是消耗品，用2-3个月或表面变光滑后需更换",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
            "materials_needed": json.dumps([]),
            "tags": [1],
        },
        {
            "id": 9, "title": "延长甲制作教程 — 纸托延长法详解",
            "slug": "nail-extension-paper-form",
            "category_id": 8, "difficulty": "advanced",
            "description": "使用纸托和延长胶制作自然美观的延长甲。从纸托安装、延甲塑形到打磨定型，完整延长甲制作流程。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 45,
            "steps": json.dumps([
                {"order": 1, "title": "甲面准备", "content": "修短真甲至合适长度，打磨甲面，去除油脂。真甲过长的需要先剪短。涂底胶照灯。", "image": ""},
                {"order": 2, "title": "安装纸托", "content": "将纸托套在手指上，调整角度和位置。纸托的弧度决定了延长甲的C弧和长度。确保纸托贴合紧密无缝隙。", "image": ""},
                {"order": 3, "title": "铺延长胶（第一层）", "content": "用延甲笔取适量延长胶，从真甲与纸托交界处开始铺设，向指尖方向延伸。控制厚度均匀。照灯30秒半固化。", "image": ""},
                {"order": 4, "title": "塑形加固", "content": "第二层延长胶在指甲最高点（应力点）加厚，指尖渐薄。用笔调整C弧弧度。照灯60秒完全固化。", "image": ""},
                {"order": 5, "title": "取下纸托打磨", "content": "轻轻取下纸托，用搓条修整延长甲的形状和厚度。从侧面看应有自然的弧形过渡。粗细搓条配合打磨。", "image": ""},
                {"order": 6, "title": "上色装饰", "content": "延长甲基础完成！接下来可以涂底胶、上色、做款式，与正常美甲流程一样。", "image": ""},
            ]),
            "tips": json.dumps([
                "纸托安装是关键步骤，多练习才能掌握最佳角度",
                "应力点（指甲中段）要稍厚以增加强度，指尖要薄才自然",
                "延长胶有透明、裸色、白色可选，裸色最适合新手",
                "延长甲长度建议不超过真甲的1/2，太长容易断裂",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4, 16, 17]),
            "materials_needed": json.dumps([1, 18, 19, 20]),
            "tags": [3, 15],
        },
        {
            "id": 10, "title": "秋冬季热门 — 磨砂丝绒美甲教程",
            "slug": "matte-velvet-nails",
            "category_id": 2, "difficulty": "beginner",
            "description": "丝绒感的磨砂美甲是秋冬大热款式。使用磨砂封层即可将任何颜色转变为高级磨砂质感。搭配跳色设计时尚感拉满。",
            "cover_image": "", "video_url": "",
            "duration_minutes": 15,
            "steps": json.dumps([
                {"order": 1, "title": "基础美甲流程", "content": "按照基础美甲流程：修甲→底胶→上色2层→每步照灯。选择秋冬流行色如酒红、墨绿、深棕、灰色等。", "image": ""},
                {"order": 2, "title": "涂磨砂封层", "content": "均匀涂抹磨砂封层，注意薄涂。磨砂封层与普通封层用法相同，但固化后呈现磨砂哑光质感。照灯60秒。", "image": ""},
                {"order": 3, "title": "跳色设计（可选）", "content": "可选择1-2个手指用亮面封层做跳色对比，或者贴金属线/小铆钉增加设计感。亮面+磨砂的对比效果非常时尚。", "image": ""},
                {"order": 4, "title": "养护提示", "content": "磨砂面容易沾染污渍，避免接触深色液体。可用酒精棉轻轻擦拭清洁磨砂面。", "image": ""},
            ]),
            "tips": json.dumps([
                "磨砂封层比普通封层更容易显划痕，涂抹时要均匀平整",
                "深色磨砂比浅色磨砂更有高级感",
                "磨砂面沾到油会变亮，做家务时建议戴手套",
                "磨砂+金属饰品是最佳搭配组合",
            ]),
            "tools_needed": json.dumps([1, 2, 3, 4]),
            "materials_needed": json.dumps([1, 2, 21, 22]),
            "tags": [2, 9, 11],
        },
    ]


def get_materials():
    return [
        {"id": 1, "name": "底胶 (Base Coat)", "category": "gel", "brand": "通用", "description": "美甲第一步使用的打底胶，增强甲油胶附着力，保护甲面不受色素沉淀。分为可卸底胶和免刻磨底胶。", "usage_guide": "修甲打磨后薄涂一层，照灯30-60秒。注意包边。", "image_url": "", "price_range": "￥15-50", "is_professional": 0},
        {"id": 2, "name": "甲油胶 (Color Gel)", "category": "gel", "brand": "通用", "description": "美甲上色用胶，颜色种类丰富。常见容量5ml-15ml。分实色、半透明、珠光、闪粉等多种质地。", "usage_guide": "底胶之后薄涂，每层照灯30-60秒。一般涂2-3层。", "image_url": "", "price_range": "￥8-60/瓶", "is_professional": 0},
        {"id": 3, "name": "封层胶 (Top Coat)", "category": "gel", "brand": "通用", "description": "美甲最后一步使用的保护胶，增加亮度和持久度。分擦洗封层（需清洁液擦拭）、免洗封层和磨砂封层。", "usage_guide": "上色完成后均匀涂抹，照灯60-90秒。注意包边。免洗封层照完即完成。", "image_url": "", "price_range": "￥15-60", "is_professional": 0},
        {"id": 4, "name": "清洁液/酒精", "category": "accessory", "brand": "通用", "description": "用于清洁甲面、擦拭浮胶、修正边缘。可用75%医用酒精替代。", "usage_guide": "倒在棉花片/无尘纸上使用。", "image_url": "", "price_range": "￥5-20", "is_professional": 0},
        {"id": 5, "name": "白色甲油胶", "category": "gel", "brand": "通用", "description": "法式美甲必备的纯白色甲油胶。选择遮盖力强的白胶效果更好。", "usage_guide": "用于法式微笑线绘制，或作为浅色打底。", "image_url": "", "price_range": "￥12-40", "is_professional": 0},
        {"id": 6, "name": "裸粉色甲油胶", "category": "gel", "brand": "通用", "description": "法式美甲常用底色，自然裸粉/裸肤色。打造健康自然的甲面底色。", "usage_guide": "法式美甲打底使用，涂1-2层即可。", "image_url": "", "price_range": "￥12-40", "is_professional": 0},
        {"id": 7, "name": "猫眼甲油胶", "category": "gel", "brand": "通用", "description": "含磁性微粒的特种甲油胶，配合磁铁使用可形成猫眼光带。颜色多样：银色、金色、蓝色、绿色、红色等。", "usage_guide": "涂胶后未照灯前用磁铁吸附形成光带，然后照灯固化。", "image_url": "", "price_range": "￥18-50", "is_professional": 0},
        {"id": 8, "name": "猫眼磁铁", "category": "tool", "brand": "通用", "description": "配合猫眼胶使用的磁铁工具。常见有长方形（经典猫眼）、圆形（光晕效果）、双头磁铁等。", "usage_guide": "在未固化的猫眼胶上方2-3mm处悬停5-10秒。", "image_url": "", "price_range": "￥5-20", "is_professional": 0},
        {"id": 9, "name": "浅色甲油胶A", "category": "gel", "brand": "通用", "description": "渐变美甲用浅色/亮色甲油胶。如粉色、白色、浅蓝等。", "usage_guide": "配合海绵制作渐变效果。", "image_url": "", "price_range": "￥10-40", "is_professional": 0},
        {"id": 10, "name": "深色甲油胶B", "category": "gel", "brand": "通用", "description": "渐变美甲用深色甲油胶。如深粉、紫色、深蓝等，与浅色搭配出渐变层次。", "usage_guide": "配合海绵与浅色胶制作渐变。", "image_url": "", "price_range": "￥10-40", "is_professional": 0},
        {"id": 11, "name": "3D雕花胶", "category": "decoration", "brand": "通用", "description": "用于制作立体装饰的特种胶，质地比甲油胶硬，可塑性强。有透明、白色和彩色版本。", "usage_guide": "用雕花笔取胶塑形后照灯固化，可叠加制作立体效果。", "image_url": "", "price_range": "￥20-60", "is_professional": 1},
        {"id": 12, "name": "美甲亮钻/珍珠", "category": "decoration", "brand": "通用", "description": "装饰用平底钻、珍珠、铆钉等。各种尺寸和颜色可选。平底设计方便粘贴在甲面上。", "usage_guide": "用点钻笔或镊子蘸取少量粘钻胶贴上，照灯固化后封层。", "image_url": "", "price_range": "￥5-30/包", "is_professional": 0},
        {"id": 13, "name": "粘钻胶", "category": "accessory", "brand": "通用", "description": "专门用于粘贴美甲饰品的胶水，比普通底胶粘性更强。有液体胶和凝胶两种。", "usage_guide": "取少量点在甲面需要贴钻的位置，放上饰品，照灯固化。", "image_url": "", "price_range": "￥10-30", "is_professional": 0},
        {"id": 14, "name": "水染彩绘胶", "category": "gel", "brand": "通用", "description": "用于水染大理石纹的流动性好的专用胶。在水中能自然扩散形成图案。", "usage_guide": "滴入水面待扩散后拉花，将甲面轻触水面转印。", "image_url": "", "price_range": "￥15-40", "is_professional": 1},
        {"id": 15, "name": "黑色甲油胶", "category": "gel", "brand": "通用", "description": "大理石纹常用的勾勒线条颜色，以及猫眼美甲打底色。选择遮盖力强的黑色。", "usage_guide": "手绘大理石纹路，或作为猫眼胶的底色。", "image_url": "", "price_range": "￥12-40", "is_professional": 0},
        {"id": 16, "name": "果冻胶贴", "category": "accessory", "brand": "通用", "description": "穿戴甲专用双面胶贴，透明果冻状。粘贴方便、卸除无伤害。适合短期佩戴。", "usage_guide": "选合适大小贴在真甲上，撕保护膜后按压穿戴甲10秒。", "image_url": "", "price_range": "￥5-15/板", "is_professional": 0},
        {"id": 17, "name": "穿戴甲专用胶水", "category": "accessory", "brand": "通用", "description": "持久型穿戴甲胶水，可保持1-2周。卸除需要使用解胶剂。", "usage_guide": "真甲和甲片各涂少量胶水，对准贴上按压30秒。", "image_url": "", "price_range": "￥8-25", "is_professional": 0},
        {"id": 18, "name": "延长胶/塑形胶", "category": "gel", "brand": "通用", "description": "用于延长甲制作的专用胶，质地较硬，塑形性好。分透明、裸色、白色。", "usage_guide": "配合纸托使用，在纸托上铺设塑形后照灯固化。", "image_url": "", "price_range": "￥30-80", "is_professional": 1},
        {"id": 19, "name": "纸托", "category": "accessory", "brand": "通用", "description": "延长甲制作时套在手指上的纸质模具。一次性使用。有不同尺寸和弧度可选。", "usage_guide": "套在手指上调整角度，在上面铺设延长胶塑形。", "image_url": "", "price_range": "￥5-15/包(100片)", "is_professional": 1},
        {"id": 20, "name": "甲片", "category": "accessory", "brand": "通用", "description": "穿戴甲或延长甲使用的成品甲片。有透明、自然色、白色等。各种尺寸混合装。", "usage_guide": "选择合适的尺寸，可在甲片上直接做款式制作穿戴甲。", "image_url": "", "price_range": "￥8-30/包(500片)", "is_professional": 0},
        {"id": 21, "name": "磨砂封层胶", "category": "gel", "brand": "通用", "description": "固化后呈现磨砂哑光质感的封层胶。可将任何亮面美甲变为磨砂效果。", "usage_guide": "与普通封层用法相同，均匀薄涂后照灯60秒。", "image_url": "", "price_range": "￥18-50", "is_professional": 0},
        {"id": 22, "name": "酒红色甲油胶", "category": "gel", "brand": "通用", "description": "秋冬热门色号，磨砂效果最佳的颜色之一。浓郁复古的酒红色。", "usage_guide": "正常上色使用，搭配磨砂封层效果最佳。", "image_url": "", "price_range": "￥12-40", "is_professional": 0},
    ]


def get_tools():
    return [
        {"id": 1, "name": "指甲刀", "category": "basic", "description": "修剪指甲长度的基础工具。建议准备大号（剪指甲）和小号（修细节）各一把。", "usage_steps": json.dumps(["先用大号指甲刀剪短指甲至目标长度", "用小号指甲刀修整边角细节", "注意不要一次剪太多，分次剪更安全"]), "precautions": "选择不锈钢材质，刀口要锋利。钝刀口容易导致指甲分层。", "image_url": "", "price_range": "￥10-40"},
        {"id": 2, "name": "指甲搓条", "category": "basic", "description": "修整甲型和打磨甲缘的必备工具。常见有100/180双面粗细规格。", "usage_steps": json.dumps(["粗面（100）用于修整甲型", "细面（180）用于打磨甲面增加附着力", "45度角沿一个方向打磨，不要来回搓"]), "precautions": "消耗品，使用2-3个月或表面变光滑后需更换。", "image_url": "", "price_range": "￥3-10/支"},
        {"id": 3, "name": "海绵抛", "category": "basic", "description": "打磨甲面的软质打磨工具，比搓条更温和。用于去除甲面油脂层增加底胶附着力。", "usage_steps": json.dumps(["轻轻打磨甲面至哑光状态", "只需打磨至无光泽即可，不要过度打磨", "用后清洁甲面粉尘"]), "precautions": "选择细面海绵抛，过度打磨会损伤甲面。", "image_url": "", "price_range": "￥3-8/支"},
        {"id": 4, "name": "LED光疗灯", "category": "lamp", "description": "固化甲油胶的必需设备。LED灯固化速度快（30-60秒），不伤手。推荐功率36W-48W以上。", "usage_steps": json.dumps(["连接电源，将手指放入灯内", "选择30秒/60秒/90秒档位", "每次涂胶后将手放入照灯", "注意手不要碰到灯管/LED灯珠"]), "precautions": "UV灯和LED灯不可混用（胶也有对应类型）。LED灯最通用。", "image_url": "", "price_range": "￥40-200"},
        {"id": 5, "name": "死皮剪", "category": "basic", "description": "修剪指甲周围死皮的专业工具。刀头小巧锋利，能精准修剪倒刺和死皮。", "usage_steps": json.dumps(["先用死皮推将死皮推起", "用死皮剪轻轻剪掉推起的死皮", "只剪已脱离的死皮，不要剪到活皮"]), "precautions": "每次使用前后要消毒。刀口极锋利，小心不要剪伤皮肤。", "image_url": "", "price_range": "￥15-60"},
        {"id": 6, "name": "死皮推", "category": "basic", "description": "用于推起指甲根部死皮的工具。金属制，一头为推刀一头为铲刀。", "usage_steps": json.dumps(["泡手软化死皮后使用", "用推刀头轻轻推起甲根死皮", "再用铲刀头刮除甲面附着物"]), "precautions": "不要用力过猛，轻柔推动即可。", "image_url": "", "price_range": "￥5-20"},
        {"id": 7, "name": "拉线笔/细毛笔", "category": "painting", "description": "极细笔头的彩绘笔，用于画法式微笑线、线条图案、大理石纹等精细操作。", "usage_steps": json.dumps(["蘸取少量彩绘胶", "画线时手腕支撑在桌面保持稳定", "线条画错可用清洁液修正"]), "precautions": "使用后立即清洁，胶干在笔上会损坏笔头。", "image_url": "", "price_range": "￥8-30"},
        {"id": 8, "name": "彩绘笔套装", "category": "painting", "description": "包含不同粗细和形状的笔头，用于手绘各种图案。常见包含圆头笔、平头笔、斜头笔等。", "usage_steps": json.dumps(["根据图案选择合适笔型", "蘸取彩绘胶后先在调色板上试色", "画错可用清洁液擦掉重画"]), "precautions": "笔用完后立即用清洁液浸泡清洗。", "image_url": "", "price_range": "￥20-80/套"},
        {"id": 9, "name": "法式贴纸", "category": "auxiliary", "description": "辅助画法式微笑线的弧形贴纸。贴在指甲上可轻松画出完美法式边缘。新手必备！", "usage_steps": json.dumps(["完成底色后粘贴法式贴纸", "指尖部分涂白胶", "趁胶未干撕下贴纸", "照灯固化"]), "precautions": "贴纸要贴牢防止漏胶。撕贴纸时要小心不要碰到未干的胶。", "image_url": "", "price_range": "￥3-10/板"},
        {"id": 10, "name": "猫眼磁铁", "category": "auxiliary", "description": "配合猫眼胶使用的磁性工具。长方形用于经典直线猫眼，圆形用于光晕效果。", "usage_steps": json.dumps(["涂好猫眼胶后不照灯", "将磁铁悬于甲面2-3mm上方", "保持5-10秒至光带形成", "满意后照灯固化"]), "precautions": "磁铁不要接触未固化的胶面。离太近会吸走胶。", "image_url": "", "price_range": "￥5-20"},
        {"id": 11, "name": "化妆海绵", "category": "auxiliary", "description": "用于渐变美甲的海绵工具。密度高的海绵做出的渐变效果更细腻。", "usage_steps": json.dumps(["在海绵上并排涂两种颜色的胶", "将海绵轻轻按压在甲面上", "重复2-3次增加层次感"]), "precautions": "使用一次性海绵或每次剪掉已用部分，保证卫生。", "image_url": "", "price_range": "￥5-15/包"},
        {"id": 12, "name": "雕花笔", "category": "painting", "description": "3D雕花专用笔，笔头较硬，适合塑形和细节雕刻。通常为金属材质。", "usage_steps": json.dumps(["蘸取少量清洁液防止粘连", "取适量雕花胶", "在甲面上塑形雕刻", "照灯固化"]), "precautions": "笔头要保持湿润以便操作，但不能太湿导致胶稀释。", "image_url": "", "price_range": "￥15-40"},
        {"id": 13, "name": "拉花针/牙签", "category": "auxiliary", "description": "水染大理石纹拉花用工具。也可用牙签替代，成本更低。", "usage_steps": json.dumps(["滴胶在水面形成图案后", "用针尖轻轻划动制造大理石纹", "纹路满意后转印到甲面"]), "precautions": "动作要轻柔且快速，颜色在水中太久会凝固。", "image_url": "", "price_range": "￥2-10"},
        {"id": 14, "name": "解胶剂", "category": "auxiliary", "description": "用于卸除穿戴甲和胶水残留的溶剂。比硬撬更安全不伤真甲。", "usage_steps": json.dumps(["在穿戴甲边缘滴入解胶剂", "等待1-2分钟让胶水溶解", "从边缘轻轻撬起取下"]), "precautions": "不要用力硬撬，耐心等解胶剂发挥作用。使用后清洗手部。", "image_url": "", "price_range": "￥8-20"},
        {"id": 15, "name": "点钻笔/拾取笔", "category": "auxiliary", "description": "带粘性笔头的笔，用于拾取和放置亮钻、珍珠等小饰品。比镊子更方便精准。", "usage_steps": json.dumps(["用笔头触碰饰品将其拾起", "放置到甲面目标位置", "轻按固定后移开笔"]), "precautions": "笔头粘性会随使用减弱，可用清水清洗恢复粘性。", "image_url": "", "price_range": "￥5-15"},
        {"id": 16, "name": "延甲笔", "category": "painting", "description": "延长甲专用笔，笔头较大，适合蘸取和铺设延长胶。通常为扁平方头设计。", "usage_steps": json.dumps(["蘸取延长胶", "从甲根向指尖方向铺设", "控制厚度和弧度", "用笔调整C弧形状"]), "precautions": "笔用后立即清洁，延长胶干燥后很难清洗。", "image_url": "", "price_range": "￥15-40"},
        {"id": 17, "name": "抛光条", "category": "basic", "description": "用于指甲表面的抛光处理，让甲面变得亮泽光滑。通常为多面设计，不同粗细面配合使用。", "usage_steps": json.dumps(["先用粗面打磨不平整处", "再用细面抛光", "最后用最细面打亮", "达到自然光泽效果"]), "precautions": "不要过度抛光，会磨损甲面表层。", "image_url": "", "price_range": "￥5-15"},
    ]
