plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\28674\\phaser-rpg-game\\nail-art-academy\\frontend\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\28674\\phaser-rpg-game\\nail-art-academy\\frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]